/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PhilatelyRouteImport } from './routes/philately'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as ExpressDeliveryRouteImport } from './routes/express-delivery'
import { Route as EcommerceEliteRouteImport } from './routes/ecommerce-elite'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PhilatelyRoute = PhilatelyRouteImport.update({
  id: '/philately',
  path: '/philately',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpressDeliveryRoute = ExpressDeliveryRouteImport.update({
  id: '/express-delivery',
  path: '/express-delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const EcommerceEliteRoute = EcommerceEliteRouteImport.update({
  id: '/ecommerce-elite',
  path: '/ecommerce-elite',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/ecommerce-elite': typeof EcommerceEliteRoute
  '/express-delivery': typeof ExpressDeliveryRoute
  '/feedback': typeof FeedbackRoute
  '/philately': typeof PhilatelyRoute
  '/privacy': typeof PrivacyRoute
  '/subscription': typeof SubscriptionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/ecommerce-elite': typeof EcommerceEliteRoute
  '/express-delivery': typeof ExpressDeliveryRoute
  '/feedback': typeof FeedbackRoute
  '/philately': typeof PhilatelyRoute
  '/privacy': typeof PrivacyRoute
  '/subscription': typeof SubscriptionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/ecommerce-elite': typeof EcommerceEliteRoute
  '/express-delivery': typeof ExpressDeliveryRoute
  '/feedback': typeof FeedbackRoute
  '/philately': typeof PhilatelyRoute
  '/privacy': typeof PrivacyRoute
  '/subscription': typeof SubscriptionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/ecommerce-elite'
    | '/express-delivery'
    | '/feedback'
    | '/philately'
    | '/privacy'
    | '/subscription'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/ecommerce-elite'
    | '/express-delivery'
    | '/feedback'
    | '/philately'
    | '/privacy'
    | '/subscription'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/ecommerce-elite'
    | '/express-delivery'
    | '/feedback'
    | '/philately'
    | '/privacy'
    | '/subscription'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  EcommerceEliteRoute: typeof EcommerceEliteRoute
  ExpressDeliveryRoute: typeof ExpressDeliveryRoute
  FeedbackRoute: typeof FeedbackRoute
  PhilatelyRoute: typeof PhilatelyRoute
  PrivacyRoute: typeof PrivacyRoute
  SubscriptionRoute: typeof SubscriptionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/philately': {
      id: '/philately'
      path: '/philately'
      fullPath: '/philately'
      preLoaderRoute: typeof PhilatelyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/express-delivery': {
      id: '/express-delivery'
      path: '/express-delivery'
      fullPath: '/express-delivery'
      preLoaderRoute: typeof ExpressDeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecommerce-elite': {
      id: '/ecommerce-elite'
      path: '/ecommerce-elite'
      fullPath: '/ecommerce-elite'
      preLoaderRoute: typeof EcommerceEliteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  EcommerceEliteRoute: EcommerceEliteRoute,
  ExpressDeliveryRoute: ExpressDeliveryRoute,
  FeedbackRoute: FeedbackRoute,
  PhilatelyRoute: PhilatelyRoute,
  PrivacyRoute: PrivacyRoute,
  SubscriptionRoute: SubscriptionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
